# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XxLEziUK-rBHmu5DWMEUWH-HZm7MSb7D
"""

from google.colab import drive
drive.mount('/content/drive')

import tensorflow as tf
import os

model_path = '/content/plant_disease_recog_model_pwp.keras'
drive_path = '/content/drive/MyDrive/plant_disease_recog_model_pwp.keras'

if os.path.exists(model_path):
    # Load the model back into memory
    model = tf.keras.models.load_model(model_path)
    print('Model reloaded from local storage.')

    # Save to Google Drive
    model.save(drive_path)
    print(f'Model successfully saved to Google Drive at: {drive_path}')
else:
    print('Local model file not found. Please re-run the training cells.')

import tensorflow as tf
import os
import shutil
import kagglehub
import pandas as pd
import glob
from google.colab import drive

# --- 1. Setup / Drive ---
drive.mount('/content/drive')

# --- 2. Dataset Loading ---
IMG_SIZE = (160, 160)
BATCH_SIZE = 32

print("Checking dataset...")
# Download the dataset
dataset_root = kagglehub.dataset_download("sravanneeli/plant-leaf-diseases-dataset-with-augmentation")
print(f"Dataset root: {dataset_root}")

# The dataset classes are directly inside this sub-folder
data_dir = os.path.join(dataset_root, 'Plant_leave_diseases_dataset_with_augmentation')

if not os.path.exists(data_dir):
    raise FileNotFoundError(f"Could not find the dataset directory at {data_dir}")

print(f"Loading data from: {data_dir}")

# Use validation_split since there are no explicit train/val folders
train_dataset = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="training",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int'
)

validation_dataset = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    validation_split=0.2,
    subset="validation",
    seed=123,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    label_mode='int'
)

class_names = train_dataset.class_names
num_classes = len(class_names)
print(f"Detected {num_classes} classes.")

# --- 3. Model Paths & Backup ---
ORIGINAL_MODEL_PATH = '/content/drive/MyDrive/plant_disease_recog_model_pwp.keras'
CHECKPOINT_DIR = '/content/drive/MyDrive/plant_disease_checkpoints/'
BACKUP_PATH = '/content/drive/MyDrive/plant_disease_model_backup.keras'
LATEST_MODEL_PATH = os.path.join(CHECKPOINT_DIR, 'latest_model.keras')
BEST_MODEL_PATH = os.path.join(CHECKPOINT_DIR, 'best_model.keras')

if not os.path.exists(CHECKPOINT_DIR): os.makedirs(CHECKPOINT_DIR)
if not os.path.exists(BACKUP_PATH) and os.path.exists(ORIGINAL_MODEL_PATH):
    shutil.copy(ORIGINAL_MODEL_PATH, BACKUP_PATH)
    print("Backup of original model created.")

# --- 4. Load & Verify Model ---
def load_latest_or_original():
    checkpoints = glob.glob(os.path.join(CHECKPOINT_DIR, "plant_disease_epoch_*.keras"))
    if checkpoints:
        latest_checkpoint = max(checkpoints, key=os.path.getctime)
        print(f"Resuming from checkpoint: {latest_checkpoint}")
        return tf.keras.models.load_model(latest_checkpoint), latest_checkpoint
    print(f"Loading original model: {ORIGINAL_MODEL_PATH}")
    return tf.keras.models.load_model(ORIGINAL_MODEL_PATH), ORIGINAL_MODEL_PATH

model, loaded_path = load_latest_or_original()

# --- 5. Baseline Evaluation ---
print("\nEvaluating baseline performance...")
loss0, accuracy0 = model.evaluate(validation_dataset)

# --- 6. Configure & Recompile ---
for layer in model.layers:
    if 'efficientnet' in layer.name.lower():
        layer.trainable = True
        for l in layer.layers[:100]:
            l.trainable = False
        break

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    metrics=['accuracy']
)

# --- 7. Callbacks ---
callbacks = [
    tf.keras.callbacks.ModelCheckpoint(os.path.join(CHECKPOINT_DIR, 'plant_disease_epoch_{epoch:02d}_valacc_{val_accuracy:.4f}.keras'), monitor='val_accuracy', save_best_only=False),
    tf.keras.callbacks.ModelCheckpoint(BEST_MODEL_PATH, monitor='val_accuracy', save_best_only=True),
    tf.keras.callbacks.ModelCheckpoint(LATEST_MODEL_PATH, save_best_only=False),
    tf.keras.callbacks.CSVLogger(os.path.join(CHECKPOINT_DIR, 'training_history.csv'), append=True)
]

# --- 8. Training ---
ADDITIONAL_EPOCHS = 10
history = model.fit(train_dataset, epochs=ADDITIONAL_EPOCHS, validation_data=validation_dataset, callbacks=callbacks)

# Final Save
model.save('/content/drive/MyDrive/plant_disease_recog_model_continued_final.keras')

# --- 11. Evaluation & Comparison ---
print("\n--- FINAL EVALUATION ---")
# Use the validation_dataset defined in the training cell
final_loss, final_accuracy = model.evaluate(validation_dataset)

print(f"\nBEFORE CONTINUED TRAINING")
print(f"Validation accuracy: {accuracy0:.4f}")

print(f"\nAFTER CONTINUED TRAINING")
print(f"Validation accuracy: {final_accuracy:.4f}")

print(f"\nBEST CHECKPOINT:")
print(f"path: {BEST_MODEL_PATH}")

print(f"\nLATEST CHECKPOINT:")
print(f"path: {LATEST_MODEL_PATH}")

# --- 12. Training History Visualization ---
import matplotlib.pyplot as plt

# 'history' was created during model.fit() in the previous cell
acc = history.history['accuracy']
val_acc = history.history['val_accuracy']
loss = history.history['loss']
val_loss = history.history['val_loss']

plt.figure(figsize=(8, 8))
plt.subplot(2, 1, 1)
plt.plot(acc, label='Training Accuracy')
plt.plot(val_acc, label='Validation Accuracy')
plt.legend(loc='lower right')
plt.ylabel('Accuracy')
plt.ylim([min(plt.ylim()), 1])
plt.title('Training and Validation Accuracy')

plt.subplot(2, 1, 2)
plt.plot(loss, label='Training Loss')
plt.plot(val_loss, label='Validation Loss')
plt.legend(loc='upper right')
plt.ylabel('Cross Entropy')
plt.ylim([0, 1.0])
plt.title('Training and Validation Loss')
plt.xlabel('epoch')
plt.show()

# --- 13. Test Prediction ---
import numpy as np
import matplotlib.pyplot as plt

# Retrieve a batch of images from the validation set
image_batch, label_batch = next(iter(validation_dataset))
predictions = model.predict(image_batch)

# Apply argmax to get predicted class IDs
predicted_class_ids = np.argmax(predictions, axis=1)

plt.figure(figsize=(10, 10))
for i in range(9):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image_batch[i].numpy().astype("uint8"))
    plt.title(f"Actual: {class_names[label_batch[i]]}\nPred: {class_names[predicted_class_ids[i]]}")
    plt.axis("off")
plt.tight_layout()
plt.show()

#further standard model requires to train on more dataset to be accurate